{"asctime": "2025-03-13 22:17:39,843", "levelname": "INFO", "pathname": "E:\\Dropbox\\GitHub\\ap_rest_client\\src\\ap_rest_client\\logging_config.py", "module": "logging_config", "funcName": "configure_logging", "message": "Client logging is initialized.", "exc_info": null, "log_destination": "E:\\Dropbox\\GitHub\\ap_rest_client\\src\\ap_rest_client\\logs\\graph_client.log"}
{"asctime": "2025-03-13 22:17:39,844", "levelname": "WARNING", "pathname": "E:\\Dropbox\\GitHub\\ap_rest_client\\src\\ap_rest_client\\ap_protocol.py", "module": "ap_protocol", "funcName": "load_environment_variables", "message": "No .env file found. Ensure environment variables are set.", "exc_info": null}
{"asctime": "2025-03-13 22:17:39,846", "levelname": "INFO", "pathname": "E:\\Dropbox\\GitHub\\ap_rest_client\\src\\ap_rest_client\\ap_protocol.py", "module": "ap_protocol", "funcName": "main", "message": "", "exc_info": null, "event": "invoking_graph", "inputs": {"messages": ["content='Write a story about a cat' additional_kwargs={} response_metadata={}"]}}
{"asctime": "2025-03-13 22:17:39,856", "levelname": "INFO", "pathname": "E:\\Dropbox\\GitHub\\ap_rest_client\\src\\ap_rest_client\\ap_protocol.py", "module": "ap_protocol", "funcName": "node_remote_agent", "message": "{\"event\": \"sending_request\", \"human\": \"Write a story about a cat\"}", "exc_info": null}
{"asctime": "2025-03-13 22:17:41,895", "levelname": "ERROR", "pathname": "E:\\Dropbox\\GitHub\\ap_rest_client\\src\\ap_rest_client\\ap_protocol.py", "module": "ap_protocol", "funcName": "node_remote_agent", "message": "{\"error\": \"Connection timeout or failure\", \"exception\": \"HTTPConnectionPool(host='127.0.0.1', port=8123): Max retries exceeded with url: /api/v1/runs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001353AEACEC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\"}", "exc_info": null}
{"asctime": "2025-03-13 22:17:41,896", "levelname": "INFO", "pathname": "E:\\Dropbox\\GitHub\\ap_rest_client\\src\\ap_rest_client\\ap_protocol.py", "module": "ap_protocol", "funcName": "exception_node", "message": "Exception happen while processing graph: {\"error\": \"Connection timeout or failure\", \"exception\": \"HTTPConnectionPool(host='127.0.0.1', port=8123): Max retries exceeded with url: /api/v1/runs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001353AEACEC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\"}", "exc_info": null}
{"asctime": "2025-03-13 22:17:41,896", "levelname": "INFO", "pathname": "E:\\Dropbox\\GitHub\\ap_rest_client\\src\\ap_rest_client\\ap_protocol.py", "module": "ap_protocol", "funcName": "main", "message": "", "exc_info": null, "event": "final_result", "result": {"messages": ["content='Write a story about a cat' additional_kwargs={} response_metadata={} id='5481b9e0-8796-4af9-8d66-987af8a149a2'"], "exception_msg": "{\"error\": \"Connection timeout or failure\", \"exception\": \"HTTPConnectionPool(host='127.0.0.1', port=8123): Max retries exceeded with url: /api/v1/runs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001353AEACEC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\"}"}}
